nelmio_cors:
    defaults:
        origin_regex: true
        allow_origin: ["%env(CORS_ALLOW_ORIGIN)%"]
        allow_credentials: true
        allow_methods: ["GET", "POST", "PUT", "PATCH", "DELETE", "OPTIONS"]
        allow_headers: ["Content-Type", "Authorization"]
        max_age: 3600

    paths:
        "^/api/":
            origin_regex: true
            allow_origin: ["%env(CORS_ALLOW_ORIGIN)%"]
            allow_credentials: true
