nelmio_cors:
    defaults:
        origin_regex: true
        allow_origin: ["http://localhost:4200"]
        allow_credentials: true
        allow_methods: ["GET", "POST", "PUT", "PATCH", "DELETE", "OPTIONS"]
        allow_headers: ["Content-Type", "Authorization"]
        expose_headers: []
        max_age: 3600
    paths:
        "^/api/":
            origin_regex: true
            allow_origin: ["http://localhost:4200"]
            allow_credentials: true
            allow_headers: ["Content-Type", "Authorization"]
            allow_methods: ["GET", "POST", "PUT", "PATCH", "DELETE", "OPTIONS"]
            max_age: 3600
